# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install anteater --no-cache-dir

services:
  - redis-server

before_script:
  - git diff --name-only HEAD^ > ./patch
  - anteater --version

script:
  - anteater --ips --urls --bincheck --project antest --patchset ./patch
